### Numpy kütüphanesini import etmek

In [2]:
import numpy as np

# Diziler

![alt text](https://miro.medium.com/max/1400/1*X0Dg7QfSYtWhSAu-afi8-g.png)
Kaynak : https://towardsdatascience.com/numpy-array-cookbook-generating-and-manipulating-arrays-in-python-2195c3988b09

In [3]:
# Tek Boyutlu Diziler
dizim = np.array([1,2,3])
dizim

array([1, 2, 3])

In [4]:
# İki Boyutlu Diziler
dizim_2d = np.array([[1,2,3],[4,5,6]])
dizim_2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Üç Boyutlu Diziler
dizim_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
dizim_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
# Farklı dizi oluşturma yöntemleri
#ones
ones = np.ones((3,4))
ones.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
#zeros
zeros = np.zeros((2,3,4),dtype=np.int8)
zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [8]:
#random
diziRnd = np.random.random((2,2))
diziRnd

array([[0.34297062, 0.68921023],
       [0.33176256, 0.1602145 ]])

In [9]:
#empty
empty =  np.empty((2,2))
empty

array([[0.34297062, 0.68921023],
       [0.33176256, 0.1602145 ]])

In [10]:
#full
full = np.full((2,2),7)
full

array([[7, 7],
       [7, 7]])

In [11]:
#arange
np.arange(10,25,5)

array([10, 15, 20])

In [12]:
#eye
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#linspace
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [14]:
#identity
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# numpy ve dosyalama

In [15]:
#colab'a dosya yükleme
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [16]:
#np.loadtxt
x,y,z = np.loadtxt('/content/drive/My Drive/Dokumanlar/veri.txt',skiprows=1,unpack=True,delimiter=",")
x,y,z

(array([0.2536, 0.4839, 0.1292, 0.1781, 0.6253]),
 array([0.1008, 0.4536, 0.6875, 0.3049, 0.3486]),
 array([0.3857, 0.3561, 0.5929, 0.8928, 0.8791]))

In [17]:
#np.genfromtxt
x,y,z = np.genfromtxt('/content/drive/My Drive/Dokumanlar/veri.txt',unpack=True,delimiter=",",filling_values=-99,skip_header=1)
x,y,z

(array([0.2536, 0.4839, 0.1292, 0.1781, 0.6253]),
 array([0.1008, 0.4536, 0.6875, 0.3049, 0.3486]),
 array([0.3857, 0.3561, 0.5929, 0.8928, 0.8791]))

In [18]:
#np.savetxt
dizi_1 = np.arange(0.0,5.0,1.0)
np.savetxt('/content/drive/My Drive/Dokumanlar/yeni2.txt',dizi_1,delimiter=",")

In [19]:
drive.flush_and_unmount()

# Dizilerde İşlemler

## Aritmetik İşlemler

In [20]:
# Dizilerin özelliklerini sorgulama  dtype,size,ndim,shape
x = np.random.randint(0,20,size=(3,4))
y = np.ones((3,4))

In [21]:
x.dtype,x.size,x.ndim,x.shape

(dtype('int64'), 12, 2, (3, 4))

In [22]:
y.dtype,y.size,y.ndim,y.shape

(dtype('float64'), 12, 2, (3, 4))

In [23]:
x+y

array([[ 1.,  5., 16., 15.],
       [11.,  8.,  3., 11.],
       [11.,  9., 11., 15.]])

In [24]:
# Broadcasting
x = np.ones((3,4))
y = np.arange(4)
x-y

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [25]:
y = np.random.random((5,1,4))
(x+y).shape

(5, 3, 4)

In [26]:
x = np.random.randint(0,20,size=(3,4))
y = np.ones((3,4))
x,y

(array([[ 4,  0,  1,  6],
        [ 3, 17,  4,  2],
        [12,  7, 12, 14]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [27]:
# np.add ya da +
np.add(x,y)

array([[ 5.,  1.,  2.,  7.],
       [ 4., 18.,  5.,  3.],
       [13.,  8., 13., 15.]])

In [28]:
# np.subtract ya da -
np.subtract(x,y)

array([[ 3., -1.,  0.,  5.],
       [ 2., 16.,  3.,  1.],
       [11.,  6., 11., 13.]])

In [29]:
# np.multiply ya da *
np.multiply(x,y)

array([[ 4.,  0.,  1.,  6.],
       [ 3., 17.,  4.,  2.],
       [12.,  7., 12., 14.]])

In [30]:
# np.divide ya da /
np.divide(x,y)

array([[ 4.,  0.,  1.,  6.],
       [ 3., 17.,  4.,  2.],
       [12.,  7., 12., 14.]])

In [31]:
# np.remainder ya da %
np.remainder(x,y)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# np.exp()
np.exp(x)

array([[5.45981500e+01, 1.00000000e+00, 2.71828183e+00, 4.03428793e+02],
       [2.00855369e+01, 2.41549528e+07, 5.45981500e+01, 7.38905610e+00],
       [1.62754791e+05, 1.09663316e+03, 1.62754791e+05, 1.20260428e+06]])

In [33]:
# np.sqrt()
np.sqrt(x)

array([[2.        , 0.        , 1.        , 2.44948974],
       [1.73205081, 4.12310563, 2.        , 1.41421356],
       [3.46410162, 2.64575131, 3.46410162, 3.74165739]])

In [34]:
# np.sin()
np.sin(x)

array([[-0.7568025 ,  0.        ,  0.84147098, -0.2794155 ],
       [ 0.14112001, -0.96139749, -0.7568025 ,  0.90929743],
       [-0.53657292,  0.6569866 , -0.53657292,  0.99060736]])

In [35]:
# np.cos()
np.cos(y)

array([[0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231]])

In [36]:
# np.log()
np.log(x)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([[1.38629436,       -inf, 0.        , 1.79175947],
       [1.09861229, 2.83321334, 1.38629436, 0.69314718],
       [2.48490665, 1.94591015, 2.48490665, 2.63905733]])

In [37]:
# a1.max(axis=0)
x.max()

17

In [38]:
# b.cumsum(axis=1)
print("Cumsum",x.cumsum(axis=0),sep="\n")
print("Array",x,sep="\n")

Cumsum
[[ 4  0  1  6]
 [ 7 17  5  8]
 [19 24 17 22]]
Array
[[ 4  0  1  6]
 [ 3 17  4  2]
 [12  7 12 14]]


In [39]:
# a.mean()
x.mean()

6.833333333333333

In [40]:
# b.median()
np.median(x)

5.0

In [41]:
# a.corrcoef()
np.corrcoef(x)

array([[ 1.        , -0.74714591,  0.82086631],
       [-0.74714591,  1.        , -0.97413711],
       [ 0.82086631, -0.97413711,  1.        ]])

In [42]:
# np.std(b)
np.std(x)

5.351531452667441

In [43]:
np.var(x)

28.638888888888886

## Karşılaştırma İşlemleri

In [44]:
# np.logical_or(), np.logical_not() ve  np.logical_and()
a = np.ones((2,2))
b = np.zeros((2,2))
a,b

(array([[1., 1.],
        [1., 1.]]), array([[0., 0.],
        [0., 0.]]))

In [45]:
a == b

array([[False, False],
       [False, False]])

In [46]:
np.logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [47]:
np.logical_and(a,b)

array([[False, False],
       [False, False]])

In [48]:
np.logical_not(a)

array([[False, False],
       [False, False]])

In [49]:
np.logical_xor(a,b)

array([[ True,  True],
       [ True,  True]])

In [50]:
# np.array_equal() ya da == 

## Dizilerde Erişim

In [51]:
b = np.random.randint(1,20,size=(2,5))
a = np.arange(0,10,2)
c = np.random.randint(1,20,size=(5,5,5))
# Tek Boyutlu
a[1]
# Çok Boyutlu
b[0][2],b
c[1,1,2],c
# z,x,y


(13, array([[[ 6,  2, 16, 11, 17],
         [ 7,  9, 17,  5,  9],
         [13, 16, 15, 12, 17],
         [15, 17,  2, 18, 10],
         [ 1,  7, 19,  3, 14]],
 
        [[14, 12,  8,  8,  6],
         [ 6,  5, 13,  1, 11],
         [ 5,  1, 13, 16, 19],
         [15,  5, 15, 12, 10],
         [ 8, 14,  3, 10, 17]],
 
        [[11,  7, 12,  4, 18],
         [ 9,  7,  9,  6, 10],
         [11,  7, 12,  6, 11],
         [16,  6,  3,  5, 14],
         [17, 14,  8, 15, 16]],
 
        [[ 4, 12,  1, 19, 19],
         [19, 17, 11, 17, 13],
         [18, 16, 11,  9,  7],
         [ 4, 12,  4,  5, 16],
         [17, 13,  5, 13,  1]],
 
        [[ 5,  1, 19,  6,  5],
         [ 7, 16, 16, 16,  2],
         [ 6,  8, 18,  6,  3],
         [ 4,  2,  1, 14,  7],
         [ 7,  9,  8,  2, 18]]]))

In [52]:
# slicing
print(c)
print(c[:1,:1,:1])

[[[ 6  2 16 11 17]
  [ 7  9 17  5  9]
  [13 16 15 12 17]
  [15 17  2 18 10]
  [ 1  7 19  3 14]]

 [[14 12  8  8  6]
  [ 6  5 13  1 11]
  [ 5  1 13 16 19]
  [15  5 15 12 10]
  [ 8 14  3 10 17]]

 [[11  7 12  4 18]
  [ 9  7  9  6 10]
  [11  7 12  6 11]
  [16  6  3  5 14]
  [17 14  8 15 16]]

 [[ 4 12  1 19 19]
  [19 17 11 17 13]
  [18 16 11  9  7]
  [ 4 12  4  5 16]
  [17 13  5 13  1]]

 [[ 5  1 19  6  5]
  [ 7 16 16 16  2]
  [ 6  8 18  6  3]
  [ 4  2  1 14  7]
  [ 7  9  8  2 18]]]
[[[6]]]


In [53]:
# [1,...] ya da [1,:,:]
c[1,...] 

array([[14, 12,  8,  8,  6],
       [ 6,  5, 13,  1, 11],
       [ 5,  1, 13, 16, 19],
       [15,  5, 15, 12, 10],
       [ 8, 14,  3, 10, 17]])

In [54]:
# Şartlı Erişim
print(dizim_2d[dizim_2d<4])

[1 2 3]


In [55]:
# Şart Tanımlama
dorttend_buyuk = (dizim_3d<4) & (dizim_3d>=2)

In [56]:
# Tanımlanan Şartı Dizide Kullanma
print(dizim_3d[dorttend_buyuk])

[2 3]


## Dizilerde Manipülasyon

In [57]:
print(dizim_2d)
# np.transpose
np.transpose(dizim_2d)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
# a.T
dizim_2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
# np.resize - a.resize
print(x)
x = np.random.randint(0,20,size=(3,4))
# np.resize(x,(6,5))
print(x.resize(6,4))

[[13 11  9 15]
 [ 0  3  1  3]
 [17  8 13  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
None


In [96]:
# np.reshape - a.reshape
x = np.random.randint(0,20,size=(3,4))
y = np.random.randint(0,20,size=(3,2,4))
(x.reshape(3,1,4)*y).shape

(3, 2, 4)

In [99]:
# a.ravel()
y.ravel()

array([17,  8, 10, 15,  2, 17, 18, 19, 16, 10,  9, 11, 19,  0, 17, 14, 15,
       13, 18,  3,  8,  0,  4, 13])

In [106]:
# np.append()
yeni_dizim = np.append(dizim,[7,8,9,10])
yeni_dizim_2d = np.append(dizim_2d,[[7],[8]],axis=1)
yeni_dizim_2d

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [110]:
# np.insert()
np.insert(dizim,1,100)

array([  1, 100,   2,   3])

In [112]:
# np.delete()
print(dizim)
np.delete(dizim,[1])

[1 2 3]


array([1, 3])

In [122]:
# np.concatenate()
x = np.random.randint(0,10,size=(5)).astype(np.int8)
np.concatenate((dizim,x))

array([1, 2, 3, 8, 1, 8, 2, 0])

In [123]:
# np.vstack()
np.vstack((dizim,dizim_2d))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [129]:
# np.hstack()
x = np.random.randint(20,size=(3,2))
y = np.random.randint(20,40,size=(3,2))
print(x)
print(y)
np.hstack((x,y))

[[ 2  2]
 [13  7]
 [ 9  2]]
[[33 39]
 [21 38]
 [32 32]]


array([[ 2,  2, 33, 39],
       [13,  7, 21, 38],
       [ 9,  2, 32, 32]])

In [131]:
# np.column_stack()
np.column_stack((x,y))

array([[ 2,  2, 33, 39],
       [13,  7, 21, 38],
       [ 9,  2, 32, 32]])

In [137]:
# np.c_[]
col_xy = np.c_[x,y]
col_xy

array([[ 2,  2, 33, 39],
       [13,  7, 21, 38],
       [ 9,  2, 32, 32]])

In [138]:
# np.r_[]
row_xy= np.r_[x,y]
row_xy

array([[ 2,  2],
       [13,  7],
       [ 9,  2],
       [33, 39],
       [21, 38],
       [32, 32]])

In [136]:
# np.hsplit()
np.hsplit(col_xy,2)

[array([[ 2,  2],
        [13,  7],
        [ 9,  2]]), array([[33, 39],
        [21, 38],
        [32, 32]])]

In [140]:
# np.vsplit()
np.vsplit(row_xy,3)

[array([[ 2,  2],
        [13,  7]]), array([[ 9,  2],
        [33, 39]]), array([[21, 38],
        [32, 32]])]

In [144]:
# np.histogram()
np.histogram(dizim_3d)

(array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1]),
 array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ]))

In [142]:
# np.dot()
x= x.reshape(2,3)
np.dot(x,y)

array([[524, 570],
       [484, 679]])

## Dizilerde Sıralama

In [146]:
# np.sort()
print(x)
np.sort(x)

[[ 2  2 13]
 [ 7  9  2]]


array([[ 2,  2, 13],
       [ 2,  7,  9]])

In [147]:
# np.argsort()
print(x)
np.argsort(x)

[[ 2  2 13]
 [ 7  9  2]]


array([[0, 1, 2],
       [2, 0, 1]])

In [148]:
# np.argmax()
np.argmax(x)

2

In [149]:
# np.argmin()
np.argmin(x)

0

# Farklı Bir örnek

In [80]:
# resim yükleme
# from google.colab import files

# uploaded = files.upload()

# for fn in uploaded.keys():
#   print('User uploaded file "{name}" with length {length} bytes'.format(
#       name=fn, length=len(uploaded[fn])))
  

In [156]:
from matplotlib.image import imread
res1 = imread('/content/drive/My Drive/Dokumanlar/car.jpg')
res2 = imread('/content/drive/My Drive/Dokumanlar/dog.jpg')
res1,res2

(array([[[141, 162, 191],
         [138, 159, 188],
         [130, 154, 182],
         ...,
         [ 68,  52,  36],
         [ 68,  55,  39],
         [ 65,  53,  39]],
 
        [[140, 161, 190],
         [135, 156, 185],
         [125, 149, 177],
         ...,
         [ 72,  56,  41],
         [ 72,  59,  43],
         [ 70,  58,  44]],
 
        [[133, 154, 183],
         [128, 149, 178],
         [118, 141, 172],
         ...,
         [ 72,  56,  41],
         [ 72,  59,  43],
         [ 70,  58,  44]],
 
        ...,
 
        [[143, 135, 124],
         [138, 128, 118],
         [132, 122, 112],
         ...,
         [129, 119, 107],
         [135, 125, 113],
         [142, 132, 120]],
 
        [[144, 136, 123],
         [136, 128, 115],
         [131, 121, 111],
         ...,
         [131, 121, 109],
         [134, 124, 112],
         [140, 130, 118]],
 
        [[135, 127, 114],
         [128, 120, 107],
         [124, 114, 104],
         ...,
         [135, 125, 113],
  